apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    demo: service
spec:
  containers:
  - name: test
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selectors:
    app: nginx
    demo: service
    
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
 