apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-lb
  labels:
    app: nginx-lb
    demo: service
spec:
  containers:
  - name: test
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodes
spec:
  type: NodePort
  selector:
    app: nginx-nodesport
    demo: service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 9376