apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: my-app
    environment: production
spec:
  containers:
  - name: test
    image: nginx
    ports:
    - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    app: my-app
    environment: production
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
